### ISSUE TITLE
micro16 decopiler: ignore spaces

### ISSUE THREAD

**Issue by BMicraft** [tuwien2020/tgi-pages#26]
Es wäre sehr nice, wenn der decompiler spaces im Input zulässt, damit man die Eingabe besser überprüfen kann.

**Comment by Fancy11111** [comment]
Eigentlich hatten wir so ein replace drinnen, aber das hat ned so gut funktioniert.
Müsste ich oder jemand mit mehr Vue Kenntnissen als ich sich nochmal anschauen

**Comment by stefnotch** [comment]
Sollte der Decompiler Spaces vom Input entfernen oder sollte das nur intern passieren?

**Comment by BMicraft** [comment]
Yup, so war's gemeint. Danke :)
