### ISSUE TITLE
Extending CONTRIBUTING.md

### ISSUE THREAD

**Issue by Fancy11111** [tuwien2020/tgi-pages#39]
# Helping new Contributors
Currently, writing new features, fixing bugs and refactoring/redesigning pages is a bit intimidating at first.

Fixing bugs and refactoring is manageable, but contributing new pages or features would be a lot easier if a quick guide was provided for new devs.

- what is the project structuring (does all code for a page go into the page .ts file or is there code splitting?)
- where do new pages go
- how do I register my pages and make them findable

We should probably write a quick introduction to the project structure to make this easier for new devs.

This should not be a tutorial on how to develop with Vue, but an overview would still be helpful.

**Comment by stefnotch** [comment]
@Fancy11111 Quick heads up: I copied over the `CONTRIBUTING.md` from the other tool and edited it accordingly: https://github.com/tuwien2020/tgi-pages/blob/main/CONTRIBUTING.md
