### ISSUE TITLE
Fancier navigation

### ISSUE THREAD

**Issue by stefnotch** [tuwien2020/tgi-pages#49]
- [x] Display the page title in the navigation bar
- [x] Fuzzy search
- [ ] ~#57~ (see the issue or comment below for more infos)

**Comment by Fancy11111** [comment]
Is this a todo for launch, or something we can push to backlog?
Also, could you expand on fuzzy search?

**Comment by Fancy11111** [comment]
Although, those features should not take tooo long

**Comment by stefnotch** [comment]
> 
> 
> Is this a todo for launch, or something we can push to backlog?
> Also, could you expand on fuzzy search?

We can totally push it to the backlog.

The simplest variant of fuzzy search basically just checks if words are similar enough using the https://en.wikipedia.org/wiki/Levenshtein_distance
Of course fancier, better variants are also an option https://stackoverflow.com/questions/23305000/javascript-fuzzy-search-that-makes-sense

**Comment by Fancy11111** [comment]
Copied from Pull Request: I have not found a feasible way to make enter also navigate to the page thats selected.
For now I'm happy with how it work, if someone has an idea please let me know.
For now I'll extract it to its own issue and move it to backlog
