### ISSUE TITLE
Make UrlRef work with other types

### ISSUE THREAD

**Issue by Fancy11111** [tuwien2020/tgi-pages#50]
Obviously putting a complete object in the url is pretty unreasonable, but making boolean and number work natively would be pretty great

**Comment by stefnotch** [comment]
Reminds me, I once actually used a library for putting whole objects into URLs
https://github.com/KilledByAPixel/JSONCrush

**Comment by Fancy11111** [comment]
also, looks like @YouSafe already started doing something like that in #47
