### ISSUE TITLE
Colorblind friendly Colorpalette

### ISSUE THREAD

**Issue by Fancy11111** [tuwien2020/tgi-pages#60]
https://davidmathlogic.com/colorblind/#%23000000-%23E69F00-%2356B4E9-%23009E73-%23F0E442-%230072B2-%23D55E00-%23CC79A7-%235653F2-%23843b34

Links to #36

**Comment by Fancy11111** [comment]
Maybe we could use this?

https://venngage.com/blog/color-blind-friendly-palette/

https://venngage-wordpress.s3.amazonaws.com/uploads/2019/08/color-blind-friendly-palette-infographic.png

We can atleast take this as orientation

**Comment by stefnotch** [comment]
@Fancy11111 Sure, I'm open to pretty much any color palette!
We could define a few CSS variables in the `index.css` file and then use those whenever we need a color.

**Comment by stefnotch** [comment]
Fixed by #83
