### ISSUE TITLE
Offline Variant

### ISSUE THREAD

**Issue by stefnotch** [tuwien2020/tgi-pages#84]
Either with an approach like #82 or with service workers/PWAs

**Comment by stefnotch** [comment]
I just tried out https://github.com/antfu/vite-plugin-pwa . It would probably be pretty easy to get it to work, but with ~200 extra dependencies, I'm not sure if we want to use it.

**Comment by stefnotch** [comment]
Okay, using [Workbox](https://github.com/GoogleChrome/workbox) is also a bit irritating, because it ships as a ES module, but Firefox [doesn't support modules in workers](https://bugzilla.mozilla.org/show_bug.cgi?id=1247687). While the linked issue talks about web workers, the same stuff applies to service workers.

**Comment by stefnotch** [comment]
Not sure how much work implementing it ourselves would be. If we do, we could probably take quite a lot of code from `vite-plugin-pwa` (appropriately licensed, of course)

**Comment by Fancy11111** [comment]
I have a PWA Prototype up and running, look at this [branch](https://github.com/Fancy11111/tgi-pages/tree/raw-pwa-prototype) 

Here is my gh-pages deployment
https://fancy11111.github.io/tgi-pages/#/

**Comment by Fancy11111** [comment]
To also document this here, the PWA had the nice side effect that we have a "desktop" variant as well.
![image](https://user-images.githubusercontent.com/15055567/141008117-c58932b1-d58d-4669-9397-6d70c477eefe.png)
![image](https://user-images.githubusercontent.com/15055567/141008167-491c0d74-3023-4c0e-9e98-e0d8bd49cd59.png)
![image](https://user-images.githubusercontent.com/15055567/141008333-16e3cde1-c577-4d3c-b78e-99fa2238631a.png)

Which makes the PWA feature close this, and #82

**Comment by Fancy11111** [comment]
I'll close this for now
